server:
  port: 80

spring:
  application:
    name: cloud-consumer-order

eureka:
  client:
    register-with-eureka: true    # true 表示将自己 向 注册中心注册
    fetch-registry: true     #是否 从Eurekaserver抓取已有的注册信息,默以为true。单节点无所调,集群必须设置为true能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka    #集群版
      #defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: consumer80
    prefer-ip-address: true   #访问路径可以显示IP地址