#8004表示注册到zookeeper服务器的支付服务提供者端口号
server:
  port: 80
#服务别名---注册zookeeper到注册中心名称
spring:
  application:
    name: cloud-consumerzk-order80
  cloud:
    zookeeper:
      connect-string: 152.136.233.99:2181
