server:
  port: 80
spring:
  application:
    name: cloud-consumerconsul-order
  ####  consul 的注册中心
  cloud:
    consul:
      host: 152.136.233.99
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true